#!/bin/bash
echo "====================================="
echo "Welcome to the calculator"
echo "--------------------"
echo "A demo of case statements"
echo "--------------------"
echo "====================================="
echo "Enter number 1"
read one
echo
read -p "Enter number 2: " two

echo "What operation do you want to do"
echo

echo "Addition (+)"
echo "Subtraction (-)"
echo "Multiplication (*)"
echo "Division (/)"



addition(){
  echo $(( $one + $two));
}

subtraction(){
	echo $(( $one - $two));
}

multiplication(){
	echo  $(($one * $two));
}

division(){
	if [ "$two" -eq 0 ];
	then
		echo "Division by zero not allowed"
	else

		echo "scale=2;  $one / $two" | bc
	fi
}

read -p "Enter the operation that you  want: " op

echo 
echo
echo "==========="
echo "RESULTS"
echo "==========="

case $op in
	+) addition;;
	-) subtraction;;
	\*) multiplication;;
	/) division;;
	*) echo "Invalid operation"
esac
